# Netlify Configuration

[build]
  publish = "dist"
  command = "npm run build"

# Form notifications
[[plugins]]
  package = "@netlify/plugin-forms"

# Redirect rules
[[redirects]]
  from = "/contact-success"
  to = "/contact"
  status = 200
  force = false
